apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: forbid-master-role
  annotations:
    policies.kyverno.io/title: forbid-master-role
    policies.kyverno.io/category: Sample
    policies.kyverno.io/description: >-
      This policy prevents changes or deletions to label called `edgefarm.tenant` on
      cluster nodes. Use of this policy requires removal of the Node resource filter
      in the Kyverno ConfigMap ([Node,*,*]). Due to Kubernetes CVE-2021-25735, this policy
      requires, at minimum, one of the following versions of Kubernetes:
      v1.18.18, v1.19.10, v1.20.6, or v1.21.0.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: prevent-label-set
    match:
      resources:
        kinds:
        - Node
    preconditions:
    - key: "{{ request.operation }}"
      operator: Equals
      value: UPDATE
    - key: "{{ request.object.metadata.labels.edgefarm.io/tenant }}"
      operator: Equals
      value: "master"
    validate:
      message: "Changing the `edgefarm.io/tenant` label on a Node is not allowed."
      deny: {}