apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict_pod_to_namespace_for_nodes
  annotations:
    policies.kyverno.io/title: Add nodeSelector
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
            Restricts scheduling of workload that has been applied to a given namespace by using labels
spec:
  background: false
  rules:
  - name: restrict_pod_to_namespace_for_nodes
    match:
      resources:
        kinds:
        - Pod
    preconditions:
    - key: "{{ request.oldObject.metadata.labels.edgefarm.tenant }}"
      operator: "Equals"
      value: "tenant1"
    # Adds the `nodeSelector` field to any Pod with two labels.
    mutate:
      patchStrategicMerge:
        spec:
          nodeSelector:
            edgefarm.tenant: tenant1