apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcore
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
data:
  cloudcore.yaml: |
    apiVersion: cloudcore.config.kubeedge.io/v1alpha2
    kind: CloudCore
    kubeAPIConfig:
      kubeConfig: ""
      master: ""
    modules:
      cloudHub:
        {{- with .Values.cloudHub.dnsNames }}
        dnsNames:
        {{ toYaml . | indent 2 }}
        {{- end }}
        https:
          address: 0.0.0.0
          enable: true
          port: {{ .Values.cloudHub.https.port }}
        nodeLimit: 1000
        tlsCAFile: /etc/kubeedge/ca/rootCA.crt
        tlsCertFile: /etc/kubeedge/certs/edge.crt
        tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key
        unixsocket:
          address: unix:///var/lib/kubeedge/kubeedge.sock
          enable: true
        websocket:
          address: 0.0.0.0
          enable: true
          port: {{ .Values.cloudHub.websocket.port }}
        cloudStream:
          enable: true
          streamPort: {{ .Values.cloudHub.stream.port }}
          tlsStreamCAFile: /etc/kubeedge/ca/rootCA.crt
          tlsStreamCertFile: /etc/kubeedge/certs/edge.crt
          tlsStreamPrivateKeyFile: /etc/kubeedge/certs/edge.key
          tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
          tlsTunnelCertFile: /etc/kubeedge/certs/edge.crt
          tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/edge.key
          tunnelPort: {{ .Values.cloudHub.tunnel.port }}
