apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  ports:
  - port: 10002
    name: https
  - port: 10000
    name: wss
  - port: 10003
    name: wss
  - port: 10004
    name: wss
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: {{ .Values.service.type }} 
{{ if .Values.loadBalancerIp }}
  loadBalancerIP: {{ .Values.loadBalancerIp }}
{{ end }}