apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
          name: "http-server"
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-volume
  volumes:
    - name: nginx-volume
      # see https://kubernetes.io/docs/concepts/storage/volumes/#hostpath for more hostPath options
      hostPath:
        path: /data
        type: DirectoryOrCreate

      # only schedule this on devices that have a specific label
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: name
                operator: In
                values:
                  - hetzner0
  # only schedule this on kubeedge devices
  tolerations:
    - key: "edgefarm.applications"
      operator: "Exists"
      effect: "NoExecute"
