apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: persistentvolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: edgefarm.io/persistentvolume
            operator: Exists