apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: protect-node-label-edgefarm.tenant
  annotations:
    policies.kyverno.io/title: Restrict node label changes
    policies.kyverno.io/category: Sample
    policies.kyverno.io/description: >-
      This policy prevents changes or deletions to label called `edgefarm.tenant` on
      cluster nodes. Use of this policy requires removal of the Node resource filter
      in the Kyverno ConfigMap ([Node,*,*]). Due to Kubernetes CVE-2021-25735, this policy
      requires, at minimum, one of the following versions of Kubernetes:
      v1.18.18, v1.19.10, v1.20.6, or v1.21.0.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: prevent-label-value-changes
    match:
      resources:
        kinds:
        - Node
    validate:
      message: "Modifying the `edgefarm.tenant` label on a Node is not allowed."
      deny:
        conditions:
        - key: "{{ request.object.metadata.labels.edgefarm.tenant }}"
          operator: "NotEquals"
          value: ""
        - key: "{{ request.object.metadata.labels.edgefarm.tenant }}"
          operator: "NotEquals"
          value: "{{ request.oldObject.metadata.labels.edgefarm.tenant }}"
  - name: prevent-label-key-removal
    match:
      resources:
        kinds:
        - Node
    preconditions:
    - key: "{{ request.operation }}"
      operator: "Equals"
      value: UPDATE
    - key: "{{ request.oldObject.metadata.labels.edgefarm.tenant }}"
      operator: "Equals"
      value: "*"
    validate:
      message: "Removing the `edgefarm.tenant` label on a Node is not allowed."
      pattern:
        metadata:
          labels:
            edgefarm.tenant: "*"