apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  ports:
  - port: 10002
    nodePort: 30002
    name: https
  - port: 10000
    nodePort: 30000
    name: wss
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: LoadBalancer
  loadBalancerIP: 123.123.123.123
