kind: Namespace
apiVersion: v1
metadata:
  name: tenant1
  labels:
    name: tenant1
---
apiVersion: v1
kind: Service
metadata:
  name: tenant1-cluster
  namespace: tenant1
spec:
  selector:
    app: vcluster
    release: tenant1
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer