# this is only needed for a setup using gardner
# this is not needed when using Kubermatic Kubernets Platform CE
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-vcluster
parameters:
  kind: managed
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/region
    values:
    - germanywestcentral
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - germanywestcentral-2
