apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simplenginx
spec:
  selector:
    matchLabels:
      simplenginx: simplenginx
  template:
    metadata:
      labels:
        simplenginx: simplenginx
    spec:
      containers:
      - name: simplenginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 8080
      # only schedule this on devices that have a specific label
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: edgefarm.io/simplenginx
                operator: Exists
      # only schedule this on kubeedge devices
      tolerations:
        - key: "node-role.kubernetes.io/edge"
          operator: "Exists"
          effect: "NoExecute"
